#!/usr/bin/env bash
set -euo pipefail

# Bootstrap k8s-steampipe skill
#
# This script:
# 1. Runs shared k8s bootstrap to generate kubeconfig
# 2. Generates steampipe kubernetes.spc with one connection per cluster
# 3. Installs kubernetes plugin if needed
#
# Usage: ./bootstrap.sh
#
# Prerequisites:
# - yq CLI installed (brew install yq)
# - steampipe CLI installed
# - kubectl installed
# - aws-vault and/or kubelogin configured for auth

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/k8s-common.sh"

echo "=== K8s Steampipe - Bootstrap ==="
echo ""

# --- Run shared bootstrap ---
"$SCRIPT_DIR/../../../lib/k8s/bootstrap.sh"

echo ""
echo "=== Generating Steampipe Config ==="
echo ""

# --- Dependency checks ---
k8s::require_steampipe

# --- Setup steampipe directories ---
mkdir -p "$STEAMPIPE_DIR/config"

# --- Get merged registry ---
merged=$(k8s::merge_registries)
anchors=$(echo "$merged" | yq -r '.clusters[].anchor')

# --- Generate steampipe config ---
spc_file="$STEAMPIPE_DIR/config/kubernetes.spc"

cat > "$spc_file" << 'HEADER'
# Auto-generated by k8s-steampipe bootstrap.sh
# Do not edit manually - rerun bootstrap.sh to regenerate
#
# Each connection corresponds to a configured cluster.
# Query using schema: k8s_<anchor>.<table>

HEADER

# Generate connections for configured clusters
for anchor in $anchors; do
    cluster=$(echo "$merged" | yq ".clusters[] | select(.anchor == \"$anchor\")")
    override=$(echo "$cluster" | yq '.kubeconfig.override')

    # Only generate for configured clusters
    if [[ "$override" == "{}" ]] || [[ "$override" == "null" ]] || [[ -z "$override" ]]; then
        continue
    fi

    # Sanitize anchor for steampipe connection name (replace - with _)
    conn_name=$(echo "$anchor" | tr '-' '_')

    cat >> "$spc_file" << EOF
connection "k8s_$conn_name" {
    plugin = "kubernetes"
    config_path = "$KUBECONFIG_PATH"
    config_context = "$anchor"
}

EOF
done

echo "Generated: $spc_file"

# --- Install kubernetes plugin if needed ---
echo ""
export STEAMPIPE_INSTALL_DIR="$STEAMPIPE_DIR"

if [[ ! -d "$STEAMPIPE_DIR/plugins" ]] || ! ls "$STEAMPIPE_DIR/plugins/"*kubernetes* &>/dev/null 2>&1; then
    echo "Installing kubernetes plugin..."
    steampipe plugin install kubernetes
else
    echo "Kubernetes plugin already installed"
fi

# --- Initialize database if needed ---
if [[ ! -d "$STEAMPIPE_DIR/db" ]]; then
    echo ""
    echo "Initializing steampipe database..."
    steampipe service start --database-listen local --database-port "$STEAMPIPE_PORT" &>/dev/null
    sleep 2
    steampipe service stop &>/dev/null
fi

# --- Summary ---
echo ""
echo "=== Steampipe Bootstrap Complete ==="
echo ""
echo "Test with:"
echo "  $SCRIPT_DIR/k8s-steampipe.sh <cluster> tables"
echo "  $SCRIPT_DIR/k8s-steampipe.sh <cluster> query \"SELECT name FROM k8s_<cluster>.kubernetes_namespace LIMIT 5\""
