# Generated by Steampipe Azure Config Generator
# Date: 2026-01-20 16:17:55
# Total subscriptions: 113
# Company: company

# Aggregator connection - queries across all subscriptions
connection "azure_company_all" {
  type        = "aggregator"
  plugin      = "azure"
  connections = ["azure_company_*"]
}

# Individual subscription connections

# Subscription: MCG_PROD
connection "azure_company_mcg_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "75a3dd41-d85a-4130-a3bc-ef4d1baeae68"
}

# Subscription: MCG_DEV
connection "azure_company_mcg_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "98e9a6c7-c9c0-4419-bd65-2b18c741a0f4"
}

# Subscription: mcg-azr-enh-app-syn-nprod
connection "azure_company_mcg_azr_enh_app_syn_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "612bdcd2-2f1e-4d2a-9a7a-7ef06f263901"
}

# Subscription: mcg-azr-enh-app-flow-nprod
connection "azure_company_mcg_azr_enh_app_flow_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e6c9b101-4301-4d53-8365-2a468d609781"
}

# Subscription: mcg-azr-enh-app-ccs-stage
connection "azure_company_mcg_azr_enh_app_ccs_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "34416c2f-91fd-430e-97eb-65686b37bb7a"
}

# Subscription: mcg-azr-enh-app-uisvc-nprod
connection "azure_company_mcg_azr_enh_app_uisvc_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "0f8c2455-588a-47b8-a73d-c3d1a1b74254"
}

# Subscription: mcg-azr-enh-app-dssartifacts-nprod
connection "azure_company_mcg_azr_enh_app_dssartifacts_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "388a9260-ebb4-4bda-b6a3-ae686144bc5d"
}

# Subscription: mcg-azr-enh-app-davinci-stage
connection "azure_company_mcg_azr_enh_app_davinci_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "d0af461f-3f5e-4fd5-8293-dc063e5f1712"
}

# Subscription: mcg-azr-enh-app-edge-nprod
connection "azure_company_mcg_azr_enh_app_edge_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "42b1f8cf-6179-419d-baac-f3974802b0dd"
}

# Subscription: mcg-azr-enh-app-pcm-stage
connection "azure_company_mcg_azr_enh_app_pcm_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "ba059dfd-84d1-48b0-ae55-e02ac715e513"
}

# Subscription: mcg-azr-enh-app-jetfire-stage
connection "azure_company_mcg_azr_enh_app_jetfire_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "c0228125-0e87-4e1f-b0bc-4f79a22f9ae1"
}

# Subscription: mcg-azr-enh-app-datasci-nprod
connection "azure_company_mcg_azr_enh_app_datasci_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "0df47e43-b9bc-45ab-83e8-e1e73b7790cf"
}

# Subscription: mcg-azr-enh-app-cwqiicm-nprod
connection "azure_company_mcg_azr_enh_app_cwqiicm_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "8e2dedc5-a358-43b5-a7a3-179fa83e0abf"
}

# Subscription: mcg-azr-enh-app-analytics-nprod
connection "azure_company_mcg_azr_enh_app_analytics_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a3f4df7b-a189-4256-b2a8-96534836ff7b"
}

# Subscription: mcg-azr-enh-app-clientcfg-nprod
connection "azure_company_mcg_azr_enh_app_clientcfg_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "0343abd1-629c-4933-be4d-2476d5a5cb0b"
}

# Subscription: mcg-azr-enh-app-clinicalanalytics-stage
connection "azure_company_mcg_azr_enh_app_clinicalanalytics_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "4cf38bb0-d4e4-4634-b1dd-bd288337eba2"
}

# Subscription: mcg-azr-enh-app-mathomartifacts-nprod
connection "azure_company_mcg_azr_enh_app_mathomartifacts_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "d016d4f6-e09b-4e48-ab50-2833dc3bf488"
}

# Subscription: mcg-azr-enh-app-epsummary-nprod
connection "azure_company_mcg_azr_enh_app_epsummary_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "0de339d9-5916-4e7e-88d6-a94a85859f76"
}

# Subscription: mcg-azr-enh-app-secops-stage
connection "azure_company_mcg_azr_enh_app_secops_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "6c459bf6-5456-4537-8e79-4d1765c6cccd"
}

# Subscription: mcg-azr-enh-app-authoringtools-stage
connection "azure_company_mcg_azr_enh_app_authoringtools_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "6cd74c33-801b-4e38-8e9e-9941c2065f5a"
}

# Subscription: mcg-azr-enh-app-pathdtr-stage
connection "azure_company_mcg_azr_enh_app_pathdtr_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "8011e7be-bb0a-44e8-8917-d624ec21be98"
}

# Subscription: mcg-azr-enh-app-informatics-nprod
connection "azure_company_mcg_azr_enh_app_informatics_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a2596359-ea7e-4142-a21b-d7408fcc9774"
}

# Subscription: mcg-azr-enh-app-cwqiapis-stage
connection "azure_company_mcg_azr_enh_app_cwqiapis_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "469d6759-2b8b-4580-bcb1-324f0b5ef039"
}

# Subscription: mcg-azr-enh-app-tenant-stage
connection "azure_company_mcg_azr_enh_app_tenant_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b4749257-114b-404f-b42f-30e13df7dd5d"
}

# Subscription: mcg-azr-enh-app-datadogaudittrail-prod
connection "azure_company_mcg_azr_enh_app_datadogaudittrail_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1e71f897-2a48-4138-8bf1-f9f7088f8be4"
}

# Subscription: mcg-azr-enh-app-ccs-prod
connection "azure_company_mcg_azr_enh_app_ccs_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b9a6df08-9d4b-42d6-a3a6-51d66ec2a9ab"
}

# Subscription: mcg-azr-enh-app-davinci-prod
connection "azure_company_mcg_azr_enh_app_davinci_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "72a3ca71-5745-4b29-aafc-495049f559eb"
}

# Subscription: mcg-azr-enh-app-authoringtools-prod
connection "azure_company_mcg_azr_enh_app_authoringtools_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "d7d11db0-afdf-4d70-9148-b65cb1a107f2"
}

# Subscription: mcg-azr-enh-app-secops-prod
connection "azure_company_mcg_azr_enh_app_secops_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "62125cb8-81d5-43d9-a21e-de6714583e58"
}

# Subscription: mcg-azr-enh-app-clinicalinformatics-primary
connection "azure_company_mcg_azr_enh_app_clinicalinformatics_primary" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "067696e3-28e0-49a1-9035-271d18943366"
}

# Subscription: mcg-azr-enh-app-clientcfg-prod
connection "azure_company_mcg_azr_enh_app_clientcfg_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b4efe6dc-eb4d-4442-b24a-4d4b53d3b479"
}

# Subscription: mcg-azr-enh-app-syn-prod
connection "azure_company_mcg_azr_enh_app_syn_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "89484173-f608-42f8-b8d2-d5729387e436"
}

# Subscription: mcg-azr-enh-app-pcm-prod
connection "azure_company_mcg_azr_enh_app_pcm_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "47841499-0b41-4174-b24d-293f0fee9d2f"
}

# Subscription: mcg-azr-enh-app-edge-prod
connection "azure_company_mcg_azr_enh_app_edge_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "add6f0a1-4f04-46cc-882b-f39bc5a2ef57"
}

# Subscription: mcg-azr-enh-app-jetfire-prod
connection "azure_company_mcg_azr_enh_app_jetfire_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "bc3ea03d-9d73-4a7f-9cff-d12aad59e911"
}

# Subscription: mcg-azr-enh-app-tenant-prod
connection "azure_company_mcg_azr_enh_app_tenant_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b7a1c7d7-cae4-4e29-8aae-f219d96c51dc"
}

# Subscription: mcg-azr-enh-app-cwqiicm-prod
connection "azure_company_mcg_azr_enh_app_cwqiicm_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1e934250-1b0f-4834-9e0a-3733ba1d0662"
}

# Subscription: mcg-azr-enh-app-gldsvc-prod
connection "azure_company_mcg_azr_enh_app_gldsvc_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "66435650-64b1-453d-9d33-fc15781897e9"
}

# Subscription: mcg-azr-enh-app-uisvc-prod
connection "azure_company_mcg_azr_enh_app_uisvc_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b2d899fa-f764-4f78-b079-c50b3c37d2b8"
}

# Subscription: mcg-azr-enh-app-datasci-prod
connection "azure_company_mcg_azr_enh_app_datasci_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "ab19c702-f70a-4993-a3b9-3088268d760e"
}

# Subscription: mcg-azr-enh-app-cwqiapis-prod
connection "azure_company_mcg_azr_enh_app_cwqiapis_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "95529218-2114-40dd-9ee4-32f8dad259fe"
}

# Subscription: mcg-azr-enh-app-hearst-appealspoc-prod
connection "azure_company_mcg_azr_enh_app_hearst_appealspoc_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "dd182fcc-3b17-4be2-ba92-2a322e98cc38"
}

# Subscription: mcg-azr-enh-app-flow-prod
connection "azure_company_mcg_azr_enh_app_flow_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "ed55fa5f-68c4-414c-a47a-593e9bbadbc7"
}

# Subscription: mcg-azr-enh-app-epsummary-prod
connection "azure_company_mcg_azr_enh_app_epsummary_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a4dfee02-b232-4b13-9db7-f7525c1fbbfe"
}

# Subscription: mcg-azr-enh-app-dsscommon-prod
connection "azure_company_mcg_azr_enh_app_dsscommon_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "3fc332f8-9b35-49fb-84c2-9c6451e89fee"
}

# Subscription: mcg-azr-enh-app-clinicalanalytics-prod
connection "azure_company_mcg_azr_enh_app_clinicalanalytics_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e7ea1c08-6494-4f43-a302-96f69f840907"
}

# Subscription: mcg-azr-enh-app-gldsvcstage-prod
connection "azure_company_mcg_azr_enh_app_gldsvcstage_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "f43efdc6-8136-407e-8ce7-efdc8510a43c"
}

# Subscription: mcg-azr-enh-app-informatics-nonphi-prod
connection "azure_company_mcg_azr_enh_app_informatics_nonphi_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e92eedb8-d682-4ac5-a6bc-7fa7f515ef61"
}

# Subscription: mcg-azr-enh-app-pathdtr-prod
connection "azure_company_mcg_azr_enh_app_pathdtr_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "8f305731-e164-4710-b067-01ef93c60e9a"
}

# Subscription: mcg-azr-enh-app-mathomcommon-prod
connection "azure_company_mcg_azr_enh_app_mathomcommon_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "45ee5d37-dd7d-42dc-84d7-5c2c4aba7e1a"
}

# Subscription: mcg-azr-enh-app-dssshared-prod
connection "azure_company_mcg_azr_enh_app_dssshared_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "ed5fbde6-f2c6-40a3-85f3-5c35376b796c"
}

# Subscription: mcg-azr-enh-app-informatics-phi-prod
connection "azure_company_mcg_azr_enh_app_informatics_phi_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "dcde9aa5-5578-4f52-b9cb-d0a3ebf4c6e5"
}

# Subscription: mcg-azr-enh-app-infapelon-prod
connection "azure_company_mcg_azr_enh_app_infapelon_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e62fc094-a261-4f64-a7de-f7ea837e6575"
}

# Subscription: mcg-azr-enh-plt-mgt-nprod
connection "azure_company_mcg_azr_enh_plt_mgt_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "9cc6af96-9b8f-49d1-a993-cd36aa5b0f48"
}

# Subscription: mcg-azr-enh-plt-conn-prod
connection "azure_company_mcg_azr_enh_plt_conn_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a4007e29-3c9e-47b5-bdce-0c2a2e57c1c1"
}

# Subscription: mcg-azr-enh-plt-idy-prod
connection "azure_company_mcg_azr_enh_plt_idy_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "d3e46fe1-f314-4e8a-af45-ff77b4cf07f1"
}

# Subscription: mcg-azr-enh-plt-mgt-prod
connection "azure_company_mcg_azr_enh_plt_mgt_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "bdb3999e-99a6-448e-a4af-f9680e9bf652"
}

# Subscription: mcg-azr-enh-plt-cicd-prod
connection "azure_company_mcg_azr_enh_plt_cicd_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "9e0cc2f9-eb44-422d-bfa0-06b2c58d901a"
}

# Subscription: Visual Studio Enterprise
connection "azure_company_visual_studio_enterprise" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "d54aa48a-3821-4a8e-a8d5-859503f3c965"
}

# Subscription: MCG_CORP_STAGE
connection "azure_company_mcg_corp_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "7d6cb9e9-8a00-4b0c-8bc0-30ebe43d96e5"
}

# Subscription: MCG_STAGE
# (Default subscription)
connection "azure_company_mcg_stage" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1fe1fcf9-516d-4dc3-b3d9-b4e518b83838"
}

# Subscription: MCG_SHARED
connection "azure_company_mcg_shared" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a2605b0b-4b85-43ef-b46d-b47726bf6d95"
}

# Subscription: octo-azr-com-std-app-openai-nonprod
connection "azure_company_octo_azr_com_std_app_openai_nonprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "94938184-b15f-4434-a106-36fe3e400b85"
}

# Subscription: mcg-azr-std-app-cloudops-prod
connection "azure_company_mcg_azr_std_app_cloudops_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e1ad3cf5-0973-43dc-b7c6-f2d14efa41b3"
}

# Subscription: MCG_TEST
connection "azure_company_mcg_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "62c0b294-c99c-4bd1-9456-b57a104bd3a4"
}

# Subscription: mcg-azr-std-app-cloudops-nprod
connection "azure_company_mcg_azr_std_app_cloudops_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "5cc7a6f5-4a43-42fc-be21-07f8e6e8cc3a"
}

# Subscription: mcg-azr-std-app-cwqiicm-dev
connection "azure_company_mcg_azr_std_app_cwqiicm_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e97b4563-0788-4128-860d-098b3f75e6ac"
}

# Subscription: mcg-azr-std-app-jetfire-dev
connection "azure_company_mcg_azr_std_app_jetfire_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "c0e0ed2c-1044-4f91-b752-131d1a63b7e6"
}

# Subscription: mcg-azr-std-app-cwqiapis-dev
connection "azure_company_mcg_azr_std_app_cwqiapis_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "c496d097-731b-4c42-9a9c-c32adb79078a"
}

# Subscription: mcg-azr-std-app-mcgtest-nprod
connection "azure_company_mcg_azr_std_app_mcgtest_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "73e25c42-f8c1-460b-b295-95c3b8f4636f"
}

# Subscription: mcg-azr-std-app-authoringtools-dev
connection "azure_company_mcg_azr_std_app_authoringtools_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "6fc0797f-df28-4ab1-b446-d0c2116cb926"
}

# Subscription: mcg-azr-std-app-hearst-appealspoc-dev
connection "azure_company_mcg_azr_std_app_hearst_appealspoc_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e449f328-40a4-47d6-905a-712daae2929b"
}

# Subscription: mcg-azr-std-app-syn-nprod
connection "azure_company_mcg_azr_std_app_syn_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "da383812-570e-4479-b7d2-6825ec01572d"
}

# Subscription: mcg-azr-std-app-ccs-test
connection "azure_company_mcg_azr_std_app_ccs_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "9d314b11-1cf1-41d7-b416-a72c1853cf48"
}

# Subscription: mcg-azr-std-app-jetfire-test
connection "azure_company_mcg_azr_std_app_jetfire_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "71e58468-3efb-43c2-b155-e0ee69672c97"
}

# Subscription: mcg-azr-std-app-davinci-test
connection "azure_company_mcg_azr_std_app_davinci_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "381aded4-9e54-4827-9085-fcbc1efbe848"
}

# Subscription: mcg-azr-std-app-davinci-dev
connection "azure_company_mcg_azr_std_app_davinci_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "5206e915-bbc9-428a-8d8e-8c9c80f78b49"
}

# Subscription: mcg-azr-std-app-cwqiapis-test
connection "azure_company_mcg_azr_std_app_cwqiapis_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1dc2fe63-2b25-4244-8976-b770a17c6739"
}

# Subscription: mcg-azr-std-app-gldsvcdev-nprod
connection "azure_company_mcg_azr_std_app_gldsvcdev_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1f9261c2-26bb-4f86-8766-ba63277667ae"
}

# Subscription: mcg-azr-std-app-mathomcommon-nprod
connection "azure_company_mcg_azr_std_app_mathomcommon_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "687b8f69-9d45-4a3a-8b76-73f87d8825ac"
}

# Subscription: mcg-azr-std-app-cwqiicm-test
connection "azure_company_mcg_azr_std_app_cwqiicm_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "4a63aa0a-59f5-4bcd-a042-af394730db53"
}

# Subscription: mcg-azr-std-app-secops-dev
connection "azure_company_mcg_azr_std_app_secops_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "71737ac8-a0f6-473b-9227-c944bca937f9"
}

# Subscription: mcg-azr-std-app-madlab-nprod
connection "azure_company_mcg_azr_std_app_madlab_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "daba1060-93b5-4c6e-9d4a-bc1b23d25ccd"
}

# Subscription: mcg-azr-std-app-authoringtools-test
connection "azure_company_mcg_azr_std_app_authoringtools_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "73ba2891-844c-4cb6-bb2f-7ad0658d256e"
}

# Subscription: mcg-azr-std-app-dssinfra-nprod
connection "azure_company_mcg_azr_std_app_dssinfra_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "3e4bd6d0-9adb-4fa7-bb8f-0ebd20c99aa9"
}

# Subscription: mcg-azr-std-app-mathominfra-nprod
connection "azure_company_mcg_azr_std_app_mathominfra_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "00b03f1b-32aa-4429-95be-5738d3b26955"
}

# Subscription: mcg-azr-std-app-informatics-nprod
connection "azure_company_mcg_azr_std_app_informatics_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "18be3d53-c2b3-4651-b421-062a3fb7a8c3"
}

# Subscription: mcg-azr-std-app-ccs-dev
connection "azure_company_mcg_azr_std_app_ccs_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1a997dcb-3b9f-4804-8fc2-f32925b58d90"
}

# Subscription: mcg-azr-std-app-clinicalinformatics-testing
connection "azure_company_mcg_azr_std_app_clinicalinformatics_testing" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "af570fdc-dc55-4796-adfa-2997ae4722a3"
}

# Subscription: mcg-azr-std-app-tenant-test
connection "azure_company_mcg_azr_std_app_tenant_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "8903841a-8d06-4dbf-9b8f-48ed310ad4db"
}

# Subscription: mcg-azr-std-app-datasci-nprod
connection "azure_company_mcg_azr_std_app_datasci_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "69222a53-a5e6-4e0f-b378-964fe96eaa53"
}

# Subscription: mcg-azr-std-app-clinicalanalytics-test
connection "azure_company_mcg_azr_std_app_clinicalanalytics_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "235e9385-abe6-43c2-99b7-bee73b132bb5"
}

# Subscription: mcg-azr-std-app-uxedev-nprod
connection "azure_company_mcg_azr_std_app_uxedev_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "627b263f-4166-4456-ae14-1e707c7f1506"
}

# Subscription: mcg-azr-std-app-flow-nprod
connection "azure_company_mcg_azr_std_app_flow_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "eed28fdd-5867-4bb9-86d6-b11da836d460"
}

# Subscription: mcg-azr-std-app-pathdtr-test
connection "azure_company_mcg_azr_std_app_pathdtr_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "3b043d28-c1f0-4345-bd48-dff1b782a816"
}

# Subscription: mcg-azr-std-app-edge-nprod
connection "azure_company_mcg_azr_std_app_edge_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a9d940bc-be22-4793-9554-e851f47b460a"
}

# Subscription: mcg-azr-std-app-icmtest-nprod
connection "azure_company_mcg_azr_std_app_icmtest_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "90efaaa2-c43d-40c5-b0ce-821a44b28b3a"
}

# Subscription: mcg-azr-std-app-dsscommon-nprod
connection "azure_company_mcg_azr_std_app_dsscommon_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "c4b6ee45-a603-44c6-899e-2e563588673d"
}

# Subscription: mcg-azr-std-app-pcm-test
connection "azure_company_mcg_azr_std_app_pcm_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "66fec5a4-2ead-416a-bdff-fe99a1afe8af"
}

# Subscription: mcg-azr-std-app-rajlab-nprod
connection "azure_company_mcg_azr_std_app_rajlab_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "87be2857-00be-4d85-aae7-6d50e9d488d3"
}

# Subscription: mcg-azr-std-app-tenant-dev
connection "azure_company_mcg_azr_std_app_tenant_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "9aee4644-8651-4935-a33b-c2747e57f784"
}

# Subscription: mcg-azr-std-app-clinicalanalytics-dev
connection "azure_company_mcg_azr_std_app_clinicalanalytics_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "1e091e0c-3d53-4cc1-a18f-2e071b8e34d0"
}

# Subscription: mcg-azr-std-app-secops-test
connection "azure_company_mcg_azr_std_app_secops_test" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "5217b613-6f5e-45af-89dd-53b07be7eaf4"
}

# Subscription: mcg-azr-std-app-pcm-dev
connection "azure_company_mcg_azr_std_app_pcm_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "581c5893-24cd-4ded-b433-634284f2723e"
}

# Subscription: mcg-azr-std-app-pathdtr-dev
connection "azure_company_mcg_azr_std_app_pathdtr_dev" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b159f9a6-0dcb-43e0-818f-e16efe44eb2a"
}

# Subscription: mcg-azr-std-plt-conn-nprod
connection "azure_company_mcg_azr_std_plt_conn_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "e59b5292-182b-49c2-b4ca-f2060e6c5edd"
}

# Subscription: mcg-azr-std-plt-idy-nprod
connection "azure_company_mcg_azr_std_plt_idy_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "84d44904-4b0c-4b66-897f-2ea1cdbb9566"
}

# Subscription: mcg-azr-std-plt-knabblab-mgt-nprod
connection "azure_company_mcg_azr_std_plt_knabblab_mgt_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "079b9576-5ac8-4dbb-b78c-3db6cb212f2c"
}

# Subscription: mcg-azr-std-plt-mgt-nprod
connection "azure_company_mcg_azr_std_plt_mgt_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "b7308d94-87d7-480d-9ada-c6c1c01f6e8e"
}

# Subscription: mcg-azr-std-plt-cicd-nprod
connection "azure_company_mcg_azr_std_plt_cicd_nprod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "ec285aeb-6f1f-4a4b-8055-95a54af4f1b0"
}

# Subscription: hts-azr-com-std-app-unitycatalog-prod
connection "azure_company_hts_azr_com_std_app_unitycatalog_prod" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "45b32075-ceb7-410a-8aea-03b2c8db1fac"
}

# Subscription: MCG_CORP
connection "azure_company_mcg_corp" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "8a800c28-e6eb-4a14-b5b6-4b1e2fa5b141"
}

# Subscription: N/A(tenant level account)
connection "azure_company_n_a_tenant_level_account" {
  plugin          = "azure"
  tenant_id       = "a84894e7-87c5-40e3-9783-320d0334b3cc"
  subscription_id = "a84894e7-87c5-40e3-9783-320d0334b3cc"
}
