#!/usr/bin/env bash
set -euo pipefail

# Bootstrap aws-steampipe-query skill
#
# This script:
# 1. Validates user account config against shipped registry
# 2. Generates steampipe aws.spc with one connection per configured account
# 3. Installs AWS plugin if needed
#
# Usage: ./bootstrap.sh
#
# Prerequisites:
# - yq CLI installed (brew install yq)
# - steampipe CLI installed
# - User config at ~/.dataops-assistant/aws/accounts.yaml

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(dirname "$SCRIPT_DIR")"

# Paths (can be overridden via env vars for testing)
DATAOPS_DIR="${DATAOPS_ASSISTANT_DIR:-$HOME/.dataops-assistant}"
AWS_DIR="${DATAOPS_ASSISTANT_AWS_DIR:-$DATAOPS_DIR/aws}"
STEAMPIPE_DIR="${DATAOPS_ASSISTANT_AWS_STEAMPIPE_DIR:-$DATAOPS_DIR/steampipe-aws}"
STEAMPIPE_PORT="${DATAOPS_ASSISTANT_AWS_STEAMPIPE_PORT:-29195}"

SHIPPED_REGISTRY="$SKILL_ROOT/config/account-registry.yaml"
USER_CONFIG="$AWS_DIR/accounts.yaml"
SPC_FILE="$STEAMPIPE_DIR/config/aws.spc"

# --- Output helpers ---
log_info() { echo "  info $1"; }
log_warn() { echo "  WARN $1" >&2; }
log_error() { echo "  ERROR $1" >&2; }
log_conf() { echo "  conf $1"; }
log_skip() { echo "  skip $1"; }

echo "=== AWS Steampipe - Bootstrap ==="
echo ""
echo "Steampipe dir: $STEAMPIPE_DIR"
echo "User config:   $USER_CONFIG"
echo ""

# --- Dependency checks ---
if ! command -v yq &>/dev/null; then
    log_error "yq CLI not installed. Install: brew install yq"
    exit 1
fi

if ! command -v steampipe &>/dev/null; then
    log_error "steampipe CLI not installed. Install from https://steampipe.io/downloads"
    exit 1
fi

# --- Check user config exists ---
if [[ ! -f "$USER_CONFIG" ]]; then
    log_error "User config not found: $USER_CONFIG"
    echo ""
    echo "Create it with your AWS profile mappings:"
    echo ""
    cat << 'EXAMPLE'
# ~/.dataops-assistant/aws/accounts.yaml
accounts:
  - name: dss-common-dev
    profile: mcg_dev_dev_access

  - name: dss-common-prod
    profile: mcg_prod_prod_access
EXAMPLE
    echo ""
    echo "Available accounts (from registry):"
    yq -r '.accounts[].name' "$SHIPPED_REGISTRY" | sed 's/^/  - /'
    exit 1
fi

# --- Setup directories ---
mkdir -p "$STEAMPIPE_DIR/config"

# --- Load registries ---
echo "Validating account configurations..."
echo ""

# Helper function to get account_id from shipped registry by name
get_account_id() {
    local name="$1"
    yq -r ".accounts[] | select(.name == \"$name\") | .account_id" "$SHIPPED_REGISTRY"
}

# Helper function to check if account exists in shipped registry
account_exists() {
    local name="$1"
    local result
    result=$(yq -r ".accounts[] | select(.name == \"$name\") | .name" "$SHIPPED_REGISTRY")
    [[ -n "$result" ]]
}

# --- Generate steampipe config ---
cat > "$SPC_FILE" << 'HEADER'
# Auto-generated by aws-steampipe bootstrap.sh
# Do not edit manually - rerun bootstrap.sh to regenerate
#
# Each connection corresponds to a configured AWS account.
# Query using schema: aws_<account_name>.<table>
# Or use aws_all.<table> to query across all accounts.

HEADER

configured_count=0
skipped_count=0
connection_names=()

# Process each user-configured account
user_account_count=$(yq '.accounts | length // 0' "$USER_CONFIG" 2>/dev/null || echo "0")

if [[ "$user_account_count" -eq 0 ]]; then
    log_error "No accounts configured in $USER_CONFIG"
    exit 1
fi

for idx in $(seq 0 $((user_account_count - 1))); do
    entry=$(yq -o=json ".accounts[$idx]" "$USER_CONFIG")

    name=$(echo "$entry" | yq -r '.name // ""')
    profile=$(echo "$entry" | yq -r '.profile // ""')
    regions=$(echo "$entry" | yq -r '.regions // ""')

    # Validate required fields
    if [[ -z "$name" ]]; then
        log_skip "entry $idx: missing 'name' field"
        ((skipped_count++))
        continue
    fi

    if [[ -z "$profile" ]]; then
        log_skip "$name: missing 'profile' field"
        ((skipped_count++))
        continue
    fi

    # Validate account exists in registry
    if ! account_exists "$name"; then
        log_skip "$name: not found in account registry"
        ((skipped_count++))
        continue
    fi

    account_id=$(get_account_id "$name")

    # Sanitize name for connection (replace - with _)
    conn_name=$(echo "$name" | tr '-' '_')
    connection_names+=("aws_$conn_name")

    # Default regions to all if not specified
    if [[ -z "$regions" ]] || [[ "$regions" == "null" ]]; then
        regions_line='regions = ["*"]'
    else
        # Convert YAML array to HCL array
        regions_hcl=$(echo "$entry" | yq -o=json '.regions' | jq -c '.')
        regions_line="regions = $regions_hcl"
    fi

    # Write connection
    cat >> "$SPC_FILE" << EOF
# Account: $name ($account_id)
connection "aws_$conn_name" {
  plugin  = "aws"
  profile = "$profile"
  $regions_line
}

EOF

    log_conf "$name -> profile=$profile"
    ((configured_count++))
done

# --- Add aggregator if we have connections ---
if [[ ${#connection_names[@]} -gt 0 ]]; then
    cat >> "$SPC_FILE" << 'EOF'
# Aggregator - query across all configured accounts
connection "aws_all" {
  type        = "aggregator"
  plugin      = "aws"
  connections = ["aws_*"]
}
EOF
fi

echo ""
echo "Generated: $SPC_FILE"
echo "Accounts: $configured_count configured, $skipped_count skipped"

if [[ $configured_count -eq 0 ]]; then
    log_error "No valid accounts configured"
    exit 1
fi

# --- Install AWS plugin if needed ---
echo ""
export STEAMPIPE_INSTALL_DIR="$STEAMPIPE_DIR"

if [[ ! -d "$STEAMPIPE_DIR/plugins" ]] || ! ls "$STEAMPIPE_DIR/plugins/"*aws* &>/dev/null 2>&1; then
    echo "Installing AWS plugin..."
    steampipe plugin install aws
else
    echo "AWS plugin already installed"
fi

# --- Initialize database if needed ---
if [[ ! -d "$STEAMPIPE_DIR/db" ]]; then
    echo ""
    echo "Initializing steampipe database..."
    steampipe service start --database-listen local --database-port "$STEAMPIPE_PORT" &>/dev/null
    sleep 2
    steampipe service stop &>/dev/null
fi

# --- Summary ---
echo ""
echo "=== Bootstrap Complete ==="
echo ""
echo "Configured accounts:"
for conn in "${connection_names[@]}"; do
    schema=$(echo "$conn" | sed 's/^aws_//')
    echo "  - $schema"
done
echo ""
echo "Test with:"
echo "  $SCRIPT_DIR/aws-steampipe.sh accounts"
echo "  $SCRIPT_DIR/aws-steampipe.sh <account> tables"
echo "  $SCRIPT_DIR/aws-steampipe.sh <account> query \"SELECT account_id FROM aws_<account>.aws_account\""
