#!/usr/bin/env bash
# Bootstrap script for dataops-assistant plugin
#
# Creates at ~/.dataops-assistant/:
#   plugin-env.sh  - exports DATAOPS_ASSISTANT_ROOT (sourced by the wrapper)
#   run            - wrapper script (delegated to by bin wrappers)
#   bin/           - per-script wrappers for unambiguous single-path invocation
#
# SKILL.md files invoke scripts via: ~/.dataops-assistant/bin/<script>.sh [args]
# Each bin wrapper delegates to the run wrapper, which handles DATAOPS_ASSISTANT_ROOT.

set -euo pipefail

# Derive plugin root from this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Create plugin directory
PLUGIN_DIR="$HOME/.dataops-assistant"
mkdir -p "$PLUGIN_DIR"

# Write env file (sourced by the wrapper)
cat > "$PLUGIN_DIR/plugin-env.sh" << EOF
# Auto-generated by dataops-assistant plugin bootstrap
export DATAOPS_ASSISTANT_ROOT="$PLUGIN_ROOT"
EOF

# Write wrapper script
cat > "$PLUGIN_DIR/run" << 'WRAPPER_EOF'
#!/usr/bin/env bash
# Auto-generated by dataops-assistant plugin bootstrap
# Usage: ~/.dataops-assistant/run skills/path/to/script.sh [args]
set -euo pipefail
source "${HOME}/.dataops-assistant/plugin-env.sh"
exec "${DATAOPS_ASSISTANT_ROOT}/$1" "${@:2}"
WRAPPER_EOF
chmod +x "$PLUGIN_DIR/run"

# Generate per-script bin wrappers
BIN_DIR="$PLUGIN_DIR/bin"
mkdir -p "$BIN_DIR"

# Remove stale wrappers from previous runs
rm -f "$BIN_DIR"/*.sh

# Collect all eligible basenames and detect collisions
# Uses temp files to stay compatible with bash 3.x (no associative arrays)
TMPMAP="$PLUGIN_DIR/.bootstrap-map.$$"
TMPCOL="$PLUGIN_DIR/.bootstrap-col.$$"
: > "$TMPMAP"
: > "$TMPCOL"

for script in "$PLUGIN_ROOT"/skills/*/scripts/*.sh; do
    [[ ! -f "$script" ]] && continue
    base="$(basename "$script")"

    # Skip internal files
    case "$base" in
        *-common.sh|bootstrap.sh) continue ;;
    esac

    # Store path relative to PLUGIN_ROOT
    rel_path="${script#"$PLUGIN_ROOT/"}"

    if grep -q "^${base}	" "$TMPMAP" 2>/dev/null; then
        # Collision: basename already seen
        echo "$base" >> "$TMPCOL"
    else
        printf '%s\t%s\n' "$base" "$rel_path" >> "$TMPMAP"
    fi
done

# Create wrappers for non-colliding scripts
wrapper_count=0
collision_list=""
while IFS=$'\t' read -r base rel_path; do
    if grep -qx "$base" "$TMPCOL" 2>/dev/null; then
        collision_list="${collision_list:+$collision_list }$base"
        continue
    fi
    cat > "$BIN_DIR/$base" << BINEOF
#!/usr/bin/env bash
exec ~/.dataops-assistant/run $rel_path "\$@"
BINEOF
    chmod +x "$BIN_DIR/$base"
    wrapper_count=$((wrapper_count + 1))
done < "$TMPMAP"

rm -f "$TMPMAP" "$TMPCOL"

# Also write to CLAUDE_ENV_FILE if available (nice-to-have for main agent)
if [[ -n "${CLAUDE_ENV_FILE:-}" ]]; then
    echo "export DATAOPS_ASSISTANT_ROOT=\"$PLUGIN_ROOT\"" >> "$CLAUDE_ENV_FILE"
fi

echo "[bootstrap] Plugin root: $PLUGIN_ROOT" >&2
echo "[bootstrap] Wrapper: $PLUGIN_DIR/run" >&2
echo "[bootstrap] Bin wrappers: $wrapper_count scripts in $BIN_DIR" >&2
if [[ -n "$collision_list" ]]; then
    echo "[bootstrap] Collisions skipped: $collision_list" >&2
fi

exit 0
